// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { type Infer as __Infer } from 'spacetimedb';

// Import all reducer arg schemas
import AddAccountReducer from '../add_account_reducer';
import RefreshAccountReducer from '../refresh_account_reducer';
import RemoveAccountReducer from '../remove_account_reducer';

export type AddAccountParams = __Infer<typeof AddAccountReducer>;
export type RefreshAccountParams = __Infer<typeof RefreshAccountReducer>;
export type RemoveAccountParams = __Infer<typeof RemoveAccountReducer>;
