// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.u32().primaryKey(),
  login: __t.string(),
  avatarUrl: __t.string().name('avatar_url'),
  plan: __t.string(),
  accessTypeSku: __t.string().name('access_type_sku'),
  premiumPercentRemaining: __t.f64().name('premium_percent_remaining'),
  premiumUnitsRemaining: __t.u32().name('premium_units_remaining'),
  premiumEntitlement: __t.u32().name('premium_entitlement'),
  chatUnlimited: __t.bool().name('chat_unlimited'),
  completionsUnlimited: __t.bool().name('completions_unlimited'),
  quotaResetDateUtc: __t.string().name('quota_reset_date_utc'),
  lastSnapshotUtc: __t.string().name('last_snapshot_utc'),
  tokenEncrypted: __t.string().name('token_encrypted'),
});
