// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default {
  id: __t.u32(),
  premiumPercentRemaining: __t.f64(),
  premiumUnitsRemaining: __t.u32(),
  premiumEntitlement: __t.u32(),
  chatUnlimited: __t.bool(),
  completionsUnlimited: __t.bool(),
  quotaResetDateUtc: __t.string(),
  lastSnapshotUtc: __t.string(),
};
